### ISSUE TITLE
There is a problem about import Pilmoji

### ISSUE THREAD

**Issue by AirportR** [jay3332/pilmoji#12]
from pilmoji import Pilmoji
  File "/usr/local/lib/python3.8/dist-packages/pilmoji/__init__.py", line 1, in <module>
    from . import helpers, source
  File "/usr/local/lib/python3.8/dist-packages/pilmoji/helpers.py", line 7, in <module>
    from emoji import EMOJI_UNICODE
ImportError: cannot import name 'EMOJI_UNICODE' from 'emoji' (/usr/local/lib/python3.8/dist-packages/emoji/__init__.py)

My system is Ubuntu 20.04 ,pilmoji version: 2.0.1
What can I do?

**Comment by jay3332** [comment]
Being fixed by #13

**Comment by ghost** [comment]
The fix seems to have been made, but when will it be published to pypi?
