### ISSUE TITLE
Please make a pypi release of the latest version.

### ISSUE THREAD

**Issue by annihilatorrrr** [jay3332/pilmoji#15]
\venv\lib\site-packages\pilmoji\helpers.py", line 7, in <module>
    from emoji import EMOJI_UNICODE
ImportError: cannot import name 'EMOJI_UNICODE' from 'emoji'

**Comment by annihilatorrrr** [comment]
![IMG_20220818_125826](https://user-images.githubusercontent.com/75305464/185335892-6d737d10-b4de-4a96-8201-27eff7fececd.jpg)



Using emoji==2.0.0 and pilmoji==2.0.1

**Comment by annihilatorrrr** [comment]
There is no cache of the emoji package.

**Comment by hershey-harsh** [comment]
I have this problem too, a simple solution is to directly download from github using the following command:
```
pip install git+https://github.com/jay3332/pilmoji
```

**Comment by annihilatorrrr** [comment]
> I have this problem too, a simple solution is to directly download from github using the following command:
> 
> ```
> pip install git+https://github.com/jay3332/pilmoji
> ```

Ya this ik :)

**Comment by jay3332** [comment]
Released to PyPI now, https://pypi.org/project/pilmoji/2.0.2/

**Comment by annihilatorrrr** [comment]
> Released to PyPI now, https://pypi.org/project/pilmoji/2.0.2/

Thanks !
