### ISSUE TITLE
[HELP] Render text with emojis

### ISSUE THREAD

**Issue by CandreaA** [jay3332/pilmoji#16]
Hello, i'm trying to draw text with emojis to an image:

```
text =  "Hello 😄"
image = Image.open(rimg_path)
img = image.convert('RGB')
d = ImageDraw.Draw(img)
box = (565, 100, 1150, 450)
d.rectangle(box, outline="#fff")
font = ImageFont.truetype(THIS_FOLDER+"/fonts/arial.ttf", size=25)
[...]
Pilmoji(img).text((x_author,y_author), text , "#fff", font)
```

but i'm getting this error:
```
myfunction(text, author, tag)
  File "c:\Users\user\Desktop\myfile\myfile.py", line 69, in myfunction
    Pilmoji(img).text((x_author,y_author), text , "#fff", font)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\pilmoji\core.py", line 315, in text
    self.image.paste(asset, (x + ox, y + oy), asset)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\PIL\Image.py", line 1628, in paste
    self.im.paste(im, box, mask.im)
TypeError: 'float' object cannot be interpreted as an integer
```

**Comment by CandreaA** [comment]
Well the problem was that i cant use float numbers as (x,y). With Pillow i can use float numbers.
Now it works (**really really slow sometime it takes up to 20 seconds**), but:

1. **i cant use align=center (it doesnt work with pilmoji)**
2. **the default line-height property is almost the double of Pillow** Is there any way to adjust it?

**Comment by jay3332** [comment]
> 1. **i cant use align=center (it doesnt work with pilmoji)**

Alignment support is planned for 3.0

> 2. **the default line-height property is almost the double of Pillow** Is there any way to adjust it?

Pass in the `spacing` argument/kwarg with the specified line height. Since it defaults to 4, half of that would be 2.

**Comment by jay3332** [comment]
sorry, the argument was named `spacing` and not `line_height`
