### ISSUE TITLE
Custom emoji not being drawn when the length of its name is 1 letter

### ISSUE THREAD

**Issue by WitherredAway** [jay3332/pilmoji#24]
Code to reproduce
```py
with Image.new("RGBA", (128, 128), (255, 255, 255, 0)) as image:
    with Pilmoji(image) as pilmoji:
        pilmoji.text(
            xy=(0, 0),
            text=f"<:e:664509407421530114>",  # Put literally any custom emoji here with 1 letter name
            fill=(0, 0, 0),
            font=FONT,
            emoji_scale_factor=130,
            emoji_position_offset=(-1, -1),
        )
        image.save("emoji.png", "PNG")
```
This image will be a blank image:
![emoji](https://user-images.githubusercontent.com/81734495/224841617-147c3b7e-fac6-4933-9f55-f3158ba30a5e.png)

Now try this with more than 1 letter name
```py
with Image.new("RGBA", (128, 128), (255, 255, 255, 0)) as image:
    with Pilmoji(image) as pilmoji:
        pilmoji.text(
            xy=(0, 0),
            text=f"<:ee:664509407421530114>",
            fill=(0, 0, 0),
            font=FONT,
            emoji_scale_factor=130,
            emoji_position_offset=(-1, -1),
        )
        image.save("emoji.png", "PNG")
```
The image is finally the expected output:
![emoji](https://user-images.githubusercontent.com/81734495/224841819-68dd3d07-30ae-4e2c-9dd4-c1114dd39a8f.png)

*P.S. I have lost sleep and 5 years off my life because of this absurd bug*

**Comment by WitherredAway** [comment]
It is an easy enough fix on my end (to change the emoji name to 2 letters) but please for the love of god do something about this before i start pulling my own hair out

**Comment by jay3332** [comment]
Fixed in https://github.com/jay3332/pilmoji/commit/2df25493407f1d389a18f4b3e9a5fae4bd922f8a, sorry for the headaches this may have caused you

**Comment by WitherredAway** [comment]
Lmao it's okay, I was memeing. Thanks for the quick fix!
